movieproject/movieapp/urls.py
from . import views
from django.urls import path
app_name='movieapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from . models import movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name', 'desc', 'year', 'img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import movie
from . forms import MovieForm

# Create your views here.
def index(request):
    Movie=movie.objects.all()
    context={
        'movie_list': Movie
    }
    return render(request, "index.html", context)

def detail(request, movie_id):
    film=movie.objects.get(id=movie_id)
    return render(request, "detail.html", {'film': film})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        Movie=movie(name=name, desc=desc, year=year, img=img)
        Movie.save()
    return render(request, "add.html")

def update(request, id):
    Movie=movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=Movie)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request, "edit.html", {'form': form, 'Movie': Movie})

def delete(request, id):
    if request.method=="POST":
        Movie=movie.objects.get(id=id)
        Movie.delete()
        return redirect('/')
    return render(request, "delete.html",)

movieproject/templates/add.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name">
    <input type="text" name="desc" placeholder="enter desc">
    <input type="text" name="year" placeholder="enter year">
    <input type="file" name="img">
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}"

</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    are you sure want to delete this movie ? <br>
    <input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{film.img.url}}" height="300" width="300">
        </div>
        <div class="col-md-6">
            <h3>{{film.name}}</h3>
            <h5>{{film.desc}}</h5>
            <h4>{{film.year}}</h4>
            <a class="btn btn-warning" href="{% url 'movieapp:update' film.id %}">update</a><br>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' film.id %}">delete</a><br>

        </div>
    </div>
</div>

{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="200px" width="200px">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}